from importlib.metadata import PackageNotFoundError, version

from .errors import AgentSdkError, ErrorCode
from .agent_state import AgentLifecycleState
from .contracts import (
    RemoteVideoStream,
    RuntimeHttpResponse,
    VideoUploadHandle,
)
from .models import (
    AcnContext,
    AgentProfile,
    ComputeConnectionParameters,
    ComputeConstraints,
    ComputeInputFormat,
    ComputeNetworkBinding,
    ComputeRequestType,
    ComputeResources,
    ComputeRole,
    ComputeSessionRequest,
    ComputeSessionStatus,
    ComputingContext,
    ComputingSession,
    ControlAction,
    ControlActionRequest,
    ControlActionStatus,
    ControlActionTarget,
    ControlInputType,
    ControlTargetRole,
    DiscoveredAgent,
    GroupConfigSnapshot,
    GroupInfo,
    GroupMemberInfo,
    MessageReceipt,
    NetworkMessageAction,
    NetworkMessageType,
    NetworkAbility,
    OperationResult,
    RecognitionTarget,
    RecognitionTargetStatus,
    RuntimeDataPlane,
    SdkInitResult,
    Snssai,
)
from .sdk import AgentSdk

try:
    __version__ = version("agent-connect-sdk")
except PackageNotFoundError:  # Source checkout without an installed distribution.
    __version__ = "0.17.6"

__all__ = [
    "AgentSdk",
    "AgentSdkError",
    "AcnContext",
    "AgentProfile",
    "AgentLifecycleState",
    "ComputeConnectionParameters",
    "ComputeConstraints",
    "ComputeInputFormat",
    "ComputeNetworkBinding",
    "ComputeRequestType",
    "ComputeResources",
    "ComputeRole",
    "ComputeSessionRequest",
    "ComputeSessionStatus",
    "ComputingContext",
    "ComputingSession",
    "ControlAction",
    "ControlActionRequest",
    "ControlActionStatus",
    "ControlActionTarget",
    "ControlInputType",
    "ControlTargetRole",
    "DiscoveredAgent",
    "ErrorCode",
    "GroupConfigSnapshot",
    "GroupInfo",
    "GroupMemberInfo",
    "MessageReceipt",
    "NetworkMessageAction",
    "NetworkMessageType",
    "NetworkAbility",
    "OperationResult",
    "RecognitionTarget",
    "RecognitionTargetStatus",
    "RemoteVideoStream",
    "RuntimeHttpResponse",
    "RuntimeDataPlane",
    "SdkInitResult",
    "Snssai",
    "VideoUploadHandle",
    "__version__",
]
